name: First Workflow

on: 
  push:
    branches:
      - main

jobs:
  exmplr-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to our fist Github Actions Workflow!"
